---
- name: Install some base libraries and packages
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
    docker_compose_path: /usr/bin/docker-compose
    docker_users:
      - vagrant
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

...