---

- name: Install some base libraries and packages
  hosts: localhost
  become: true
  connection: local
  vars:
    pip_install_packages:
      - name: docker
    docker_compose_path: /usr/bin/docker-compose
    docker_users:
      - vagrant

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Create /opt/docker-compose directory
      file:
        state: directory
        path: /opt/docker-compose
        owner: vagrant
        group: vagrant

    - name: Install ufw packages
      pip:
        name: ufw
        state: present

    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow
        logging: medium

    - name: Enable firewall rules
      ufw:
        rule: allow
        port: "{{ port_number }}"
      loop:
        - '22'
        - '2222'
      loop_control:
        loop_var: port_number

    - name: Deny everything and reset UFW
      ufw:
        state: enabled
        policy: deny

    - name: Ensure that the UFW service is enabled on boot
      service:
        name: ufw
        enabled: true
        state: started
...
